### ISSUE TITLE
Couldn't connect to Kodi

### ISSUE THREAD

**Issue by acasanova** [StreamBoat/kodi_jsonrpc#1]
Hi, I'm trying to use your library to connect to a running instance of kodi on Macosx Mavericks.  

My kodi webserver config looks like the following
![image](https://cloud.githubusercontent.com/assets/2922800/7429990/e517068e-efd9-11e4-8a56-ec04aed1f601.png)

````
package main

import (
	"fmt"
	kodij "github.com/StreamBoat/kodi_jsonrpc"
)

func main() {
	kodi, err := kodij.New(`localhost:8097`, 15) // timeout after 15 secs
	defer kodi.Close()                           // always close to free resources

	if err != nil {
		panic(fmt.Sprintf(`Couldn't connect to Kodi: %v`, err))
	}

	request := kodij.Request{Method: `JSONRPC.Version`}
	response, _ := kodi.Send(request, true) // second param says we need a response

	// wait indefinitely for response (timeout 0)
	result, err := response.Read(0)

	if err != nil {
		panic(fmt.Sprintf(`Kodi responded with error: %v`, err))
	}

	fmt.Println(result)

	// Output:
	// map[version:map[major:6 minor:14 patch:3]]
}
````

````
INFO[0000] Connected to Kodi
ERRO[0015] Kodi responded                                error=Timeout waiting on response channel
INFO[0015] Disconnected from Kodi
panic: Couldn't connect to Kodi: Timeout waiting on response channel

goroutine 1 [running]:
main.main()
	/Users/acasanova/projects/go/src/gregbox/test/main.go:13 +0x226

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [runnable]:
net.(*pollDesc).Wait(0xc2080100d0, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080100d0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010070, 0xc20807c000, 0x200, 0x200, 0x0, 0x4119c8, 0xc20800a4d8)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208038020, 0xc20807c000, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/net.go:121 +0xdc
encoding/json.(*Decoder).readValue(0xc208076000, 0xc207ffcbbb, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/encoding/json/stream.go:124 +0x5e1
encoding/json.(*Decoder).Decode(0xc208076000, 0x164420, 0xc208034440, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/encoding/json/stream.go:44 +0x7b
github.com/StreamBoat/kodi_jsonrpc.(*Connection).reader(0xc20805c0b0)
	/Users/acasanova/projects/go/src/github.com/StreamBoat/kodi_jsonrpc/kodi_jsonrpc.go:337 +0x6c
created by github.com/StreamBoat/kodi_jsonrpc.(*Connection).init
	/Users/acasanova/projects/go/src/github.com/StreamBoat/kodi_jsonrpc/kodi_jsonrpc.go:199 +0x1d5

goroutine 6 [runnable]:
github.com/StreamBoat/kodi_jsonrpc.(*Connection).writer(0xc20805c0b0)
	/Users/acasanova/projects/go/src/github.com/StreamBoat/kodi_jsonrpc/kodi_jsonrpc.go:324 +0x7a
created by github.com/StreamBoat/kodi_jsonrpc.(*Connection).init
	/Users/acasanova/projects/go/src/github.com/StreamBoat/kodi_jsonrpc/kodi_jsonrpc.go:200 +0x1f2
exit status 2
````

If I go to http://localhost:8097/jsonrpcit loads the documentation and so on I tried some of the json rpc examples ( http://kodi.wiki/view/JSON-RPC_API/Examples ) and they seemed to work fine.
Could you provide any pointers on why this might be happening?

**Comment by pdf** [comment]
The HTTP API is deprecated, you want to use the port from the `Remote Control` screen, which is the raw JSON-RPC interface.

**Comment by acasanova** [comment]
are you referring to this view?
![image](https://cloud.githubusercontent.com/assets/2922800/7431868/bfb92770-eff0-11e4-9b6a-7a26582474e9.png)

**Comment by acasanova** [comment]
ok i turned off the webserver and it connected. Thanks

**Comment by pdf** [comment]
Hmm, web interface shouldn't need to be disabled - I have both enabled without problem.  However both of the options in your last screenshot had to be enabled for the JSON-RPC interface to work last time I tested it, even from localhost.  So if you had only the first option enabled, that might have caused your problem when you first tried port 9090.
